version: '3'

services:
  lamp-perl:
    build: .
    ports:
      - "22:22"
      - "80:80"
      - "3306:3306"
    volumes:
      - ./www:/var/www/html
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secure_root_password
    restart: unless-stopped

volumes:
  mysql-data:
